### ISSUE TITLE
Unable to write bytes to IOStream using futures

### ISSUE THREAD

**Issue by kevinpoitra** [gtk-rs/gio#195] opened 2019-02-19 13:09 UTC
I'm trying to implement a function that'll handle sending out and receiving data from a server I've written. To do so, I'm using `SocketClient`'s `connect_to_host_async_future` and `OutputStream`'s `write_all_async_future` functions. What I'm seeing is that the program is able to connect to the server, but immediately fails when trying to write anything to it. The code that I have so far looks like this:

```Rust
pub fn send_request(request: RequestBuilder) {
    let c = glib::MainContext::default();
    let l = glib::MainLoop::new(Some(&c), false);

    c.push_thread_default();

    let l_clone = l.clone();

    let client = gio::SocketClient::new();
    client.set_timeout(10);

    let req = request.build();

    c.spawn_local(
        client.connect_to_host_async_future(&request.get_host(), 80)
            .map_err(|_| {
                println!("Connection failed");
            })
            .and_then(|(s, conn)| {
                println!("Is connected: {}", &conn.is_connected());
                let stream: IOStream = conn.upcast();
                println!("Stream is closed: {}", &stream.is_closed());
                let writer = stream.get_output_stream().expect("Failed to obtain output stream");

                writer.write_all_async_future(req.into_bytes(), glib::PRIORITY_DEFAULT)
                    .map_err(|(strm, (buf, err))| {
                        println!("Write failed: {}", err);
                        dbg!(strm.is_closed());
                    })
                    .and_then(|(_strm, (buf, count, err))| {
                        dbg!(count);
                        Ok(())
                    })
            })
            .then(move |_| {
                println!("Done with connection");
                l_clone.quit();
                Ok(())
            })
    );

    println!("Going to run");

    l.run();

    println!("Ran");

    c.pop_thread_default();
}
```
which will output the following:
```
Going to run
Is connected: true
Stream is closed: false
Write failed: Stream is already closed
[src\net\mod.rs:44] strm.is_closed() = true
Done with connection
Ran
```
How is the stream closed if it was just previously opened before writing to it? From what I can tell, the stream closes after the "write failed" output message (if I insert a thread::sleep before there, the server won't show a disconnect message until after that sleep period).

**Comment by sdroege** [comment] 2019-02-19 13:25
Can you provide a small testcase that can be run to reproduce this?

**Comment by kevinpoitra** [comment] 2019-02-19 14:09
Sure thing - I've created a new repo for it, which can be found [here](https://github.com/kevinpoitra/gio-futures-test). It works very similarly to what I posted above; it'll connect to one of GitHub's servers, try to send "test" as an array of bytes to it, and receive an error when trying to perform that write operation.

**Comment by sdroege** [comment] 2019-02-19 15:07
```diff
diff --git a/src/main.rs b/src/main.rs
index 6e988d9..44454cc 100644
--- a/src/main.rs
+++ b/src/main.rs
@@ -41,6 +41,7 @@ fn main() {
                         })
                         .and_then(|(_strm, (_buf, count, _err))| {
                             dbg!(count);
+                            dbg!(stream);
                             Ok(())
                         })
                 })
```

This works around the problem. The problem is that `stream`, the `gio::SocketConnection`, is getting out of scope after your `connect_to_host_async_future()` continuation and is then destroyed. While you still have a reference to the `gio::OutputStream`, not having any reference to the connection anymore is causing it to be closed.

Quite unintuitive behaviour in `gio`, nothing to do with how the bindings work. You can easily reproduce it also with the following synchronous code:

```rust
use gio::prelude::*;

fn main() {
    let client = gio::SocketClient::new();
    client.set_timeout(10);

    let req = String::from("test");

    let conn = client.connect_to_host("192.30.253.112", 80, None::<&gio::Cancellable>).unwrap();

    println!("Is connected: {}", &conn.is_connected());
    println!("Stream is closed: {}", &conn.is_closed());
    let writer = conn.get_output_stream().expect("Failed to obtain output stream");

    // comment this out to make it work
    drop(conn);
    let res = writer.write_all(req.as_bytes(), None::<&gio::Cancellable>);
    println!("write finished: {:?}", res);
}
```

----

PS: Don't run a main context/main loop inside your `startup` signal handler. The `gio::Application` is already doing that for you and `startup` is called from an existing main loop.

**Comment by sdroege** [comment] 2019-02-19 15:14
Reported to GLib: https://gitlab.gnome.org/GNOME/glib/issues/1690

Let's close this on our side then.

**Closed by sdroege** 2019-02-19 15:14 UTC
